"""
main.py
=======
FastAPI application entrypoint for Sundari AI Mix Engineer — Phase 1
(Audio Analysis Engine).

Run locally with:
    uvicorn app.main:app --reload --port 8000

Then open http://localhost:8000/docs for interactive Swagger API docs
(auto-generated by FastAPI from the Pydantic schemas in app/models).
"""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import get_settings
from app.api.routes_analysis import router as analysis_router
from app.api.routes_report import router as report_router
from app.api.routes_decision import router as decision_router
from app.api.routes_mix import router as mix_router

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    description=(
        "AI Mixing & Mastering Engine — Phase 1: Audio Analysis Engine. "
        "Provides LUFS, peak, RMS, dynamic range, stereo width/phase, "
        "spectral band energy, and heuristic detection of mud, harshness, "
        "sibilance, clipping, bass balance, and frequency masking."
    ),
    version="0.1.0-phase1",
)

# CORS: development mein sab origins allowed hain. Production mein sirf
# ALLOWED_ORIGINS env var mein diye gaye asli website domain(s) allowed
# honge (.env / hosting panel mein set karein, jaise:
# ALLOWED_ORIGINS=https://mixsundarirecords.com,https://support.sundaricreation.com).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"] if settings.environment == "development" else settings.allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(analysis_router, prefix=settings.api_v1_prefix)
app.include_router(report_router, prefix=settings.api_v1_prefix)
app.include_router(decision_router, prefix=settings.api_v1_prefix)
app.include_router(mix_router, prefix=settings.api_v1_prefix)


@app.get("/", tags=["Health"])
async def root():
    return {
        "app": settings.app_name,
        "status": "running",
        "phase": "Phase 1 - Audio Analysis Engine",
        "docs": "/docs",
    }


@app.get("/health", tags=["Health"])
async def health():
    return {"status": "ok"}
